# harbor-auth.yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-auth
  annotations:
    tekton.dev/docker-0: https://harbor.devops.com
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
