# pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun
spec:
  serviceAccountName: tekton-build-sa
  pipelineRef:
    name: pipeline
  workspaces:
    - name: go-repo-pvc
      persistentVolumeClaim:
        claimName: go-repo-pvc
  params:
    - name: git_url
      value: "http://gitlab.devops.com/devops/golang-hello-world.git"
    - name: revision
      value: "main"
    - name: image
      value: "harbor.devops.com/devops/golang-hello-world:v0.7.0"
    - name: charts_dir
      value: "./helm/golang-hello-world"
    - name: release_name
      value: "golang-hello-world"
    - name: release_namespace
      value: "default"
    - name: overwrite_values
      value: "image.repository=harbor.devops.com/devops/golang-hello-world,image.tag=v0.7.0"
    - name: values_file
      value: "my-values.yaml"
