apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  params:
  - name: url
    value: https://github.com/PatrickPan93/spring-petclinic
  - name: revision
    value: main
  type: git
